"""Typed data contract for Entropy Loop Core.

These Pydantic models are the shared vocabulary of the *Failure Compiler*: a
task flows in, an agent produces output, a verifier judges it, and any failure
is captured as a structured :class:`FailureTrace` that can be compiled into a
reusable :class:`Lesson` and a :class:`RegressionCase`.

The models are intentionally small and dependency-light so they can be reused
by callers building their own reliability tooling.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, Field


class LoopStatus(str, Enum):
    """Final outcome of an :class:`~entropy_loop_core.loop.EntropyLoop` run."""

    SUCCESS = "success"
    FAILED = "failed"


class Severity(str, Enum):
    """How serious a verification failure is.

    Severity lets callers triage failures without parsing messages: a
    ``WARNING`` may be tolerable, an ``ERROR`` is a real defect, and a
    ``CRITICAL`` failure (for example an agent crash) should never ship.
    """

    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class Task(BaseModel):
    """A unit of work handed to an agent.

    Attributes:
        id: Stable identifier for the task; autogenerated when omitted.
        instruction: The instruction or input the agent should act on.
        metadata: Optional free-form context (for example ``expected_format``).
    """

    id: str = Field(
        default_factory=lambda: uuid4().hex[:12],
        description="Stable identifier for the task.",
    )
    instruction: str = Field(..., description="Instruction or input for the agent.")
    metadata: dict[str, str] = Field(
        default_factory=dict,
        description="Optional free-form context attached to the task.",
    )


class AgentOutput(BaseModel):
    """The raw output produced by an agent for a single attempt.

    Attributes:
        content: The textual output the agent returned.
        metadata: Optional free-form context about how it was produced.
    """

    content: str = Field(..., description="Raw textual output from the agent.")
    metadata: dict[str, str] = Field(
        default_factory=dict,
        description="Optional free-form context about the output.",
    )


class VerificationResult(BaseModel):
    """The verdict of checking a single agent output.

    Attributes:
        passed: ``True`` when every rule passed.
        reason: Explanation of the first violation, or ``None`` on success.
        rule_name: Name of the rule that produced this result.
        severity: How serious the failure is; ignored when ``passed`` is True.
    """

    passed: bool = Field(..., description="Whether verification passed.")
    reason: str | None = Field(
        default=None, description="First violation message, if any."
    )
    rule_name: str | None = Field(
        default=None, description="Name of the rule that produced this result."
    )
    severity: Severity = Field(
        default=Severity.ERROR, description="Severity of the failure."
    )


class FailureTrace(BaseModel):
    """A structured record of one failed attempt.

    A ``FailureTrace`` is the atom the compiler works on: it bundles everything
    needed to explain, remember, and regression-test a failure.

    Attributes:
        task: The task that failed.
        output: The agent output that was rejected.
        verification_result: Why the output was rejected.
        attempt: The 1-based attempt number that produced the failure.
        timestamp: When the failure was recorded (UTC).
    """

    task: Task = Field(..., description="The task that failed.")
    output: AgentOutput = Field(..., description="The rejected agent output.")
    verification_result: VerificationResult = Field(
        ..., description="Why the output was rejected."
    )
    attempt: int = Field(..., ge=1, description="1-based attempt number.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the failure was recorded (UTC).",
    )


class Lesson(BaseModel):
    """A reusable learning artifact compiled from a failure.

    Attributes:
        summary: What went wrong, in one human-readable line.
        avoid_next_time: The behavior the agent should avoid on future attempts.
        recommended_prompt_patch: A concrete instruction to add on retry.
        tags: Short keys used to match this lesson to future tasks.
    """

    summary: str = Field(..., description="What went wrong, in one line.")
    avoid_next_time: str = Field(..., description="Behavior to avoid next time.")
    recommended_prompt_patch: str = Field(
        ..., description="Concrete instruction to add on retry."
    )
    tags: list[str] = Field(
        default_factory=list, description="Keys for matching to future tasks."
    )


class RegressionCase(BaseModel):
    """A test-like artifact generated from a failure.

    A ``RegressionCase`` records a task that once failed together with the rule
    that must pass for the failure to be considered fixed, so the same mistake
    can be checked against forever.

    Attributes:
        name: A stable, identifier-friendly name for the case.
        instruction: The task instruction that triggered the failure.
        expected_rule: The verification rule that must now pass.
        failure_reason: The original failure message.
    """

    name: str = Field(..., description="Identifier-friendly name for the case.")
    instruction: str = Field(..., description="Instruction that triggered failure.")
    expected_rule: str = Field(..., description="Rule that must now pass.")
    failure_reason: str = Field(..., description="The original failure message.")


class AgentContext(BaseModel):
    """Everything an agent receives for a single attempt.

    On the first attempt ``lessons`` is empty; on retries it carries the
    lessons the loop has compiled so far, so the agent can adapt its behavior.

    Attributes:
        task: The task to act on.
        attempt: The 1-based attempt number.
        lessons: Lessons relevant to this task, most recent last.
    """

    task: Task = Field(..., description="The task to act on.")
    attempt: int = Field(..., ge=1, description="1-based attempt number.")
    lessons: list[Lesson] = Field(
        default_factory=list, description="Lessons relevant to this task."
    )


class LoopResult(BaseModel):
    """Structured result of running a task through the entropy loop.

    Attributes:
        status: Whether the loop ultimately succeeded or failed.
        attempts: Total number of attempts made.
        output: The final agent output, if the loop succeeded.
        failures: The failure traces captured along the way, in order.
        lessons: The lessons compiled from those failures, in order.
        regression_cases: Regression cases generated from failures, in order.
    """

    status: LoopStatus = Field(..., description="Final status of the loop.")
    attempts: int = Field(..., ge=0, description="Total number of attempts made.")
    output: AgentOutput | None = Field(
        default=None, description="Final agent output, if the loop succeeded."
    )
    failures: list[FailureTrace] = Field(
        default_factory=list, description="Failure traces captured, in order."
    )
    lessons: list[Lesson] = Field(
        default_factory=list, description="Lessons compiled from failures."
    )
    regression_cases: list[RegressionCase] = Field(
        default_factory=list, description="Regression cases generated from failures."
    )
